version: '3.5'

services:
    # PostgreSQL database
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image:        redis:2.8.19
    hostname:     redis

  # RabbitMQ
  rabbit:
    hostname:     rabbit
    image:        rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Django web server
  django:
    build:
      context: ./APPBackend
      dockerfile: dev.Dockerfile
    hostname: web
    command: ./run_web.sh
    volumes:
      # - .:/app  # mount current directory inside container
      - "./APPBackend/Django/config:/code/config"
      - "./APPBackend/Django/api:/code/api"
      - "./APPBackend/Django/core:/code/core"
      - "./APPBackend/static:/code/static"
      - "./workdir:/code/workdir"
      - "./tools:/code/tools"
      - "./test_packages:/code/test_packages"
      - "./APPBackend/Django/populate_database.py:/code/populate_database.py"
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "./django/populate_database.py:/populate_database.py"
#       - "./Django:/code"
    ports:
      - "80:80"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: ./APPBackend
      dockerfile: dev.Dockerfile
    command: ./run_celery.sh
    volumes:
      # - .:/app  # mount current directory inside container
      - "./APPBackend/Django/config:/code/config"
      - "./APPBackend/Django/api:/code/api"
      - "./APPBackend/Django/core:/code/core"
      - "./APPBackend/static:/code/static"
      - "./workdir:/code/workdir"
      - "./test_packages:/code/test_packages"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./tools:/code/tools"
      # - "./Django/tools:/code/tools"
#       - "./Django:/code"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit

networks:
  default:
    name: "APP_Default"
