version: '3.5'

services:

    # PostgreSQL database
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  # Redis
  redis:
    image: redis:2.8.19
    hostname: redis

    # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin


  nginx:
    # restart: always
    image: tutum/nginx
    ports:
      - "80:80"
    volumes:
      - "static_files:/code/static_root"
      - "./Nginx/sites-enabled:/etc/nginx/sites-enabled"
    links:
      - django:django

  django:
    image: axenu/app
    links:
      - db
      - rabbit
      - redis

    volumes:
      - "./workdir:/code/workdir"
      - "./tools:/code/tools"
      - "./packages:/code/packages"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "static_files:/code/static_root"
    command: ./run_django.sh #gunicorn config.wsgi:application -w 2 -b :8000


  worker:
    image: axenu/app
    command: ./run_celery.sh
    volumes:
      - "./workdir:/code/workdir"
      - "./packages:/code/packages"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./tools:/code/tools"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit

volumes:
  tools:
  static_files:
  postgres-data:

networks:
  default:
    name: "APP_Default"
