version: '2'

services:
  db:
    environment:
      POSTGRES_DB: saw_db
      POSTGRES_USER: saw
      POSTGRES_PASSWORD: pass
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  # redis:
  #   restart: always
  #   image: redis:3.0
  #   expose:
  #     - "6379"
  app:
    # environment:
      # DATABASE_URL: postgres://app_user:changeme@db/app_db
      # REDIS_URL: redis://redis
      # DJANGO_MANAGEPY_MIGRATE: on
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "80:80"
    volumes:
      - "./test_packages:/mnt/epp"
