name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build ./APPBackend --file ./APPBackend/prod.Dockerfile --tag axenu/app
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: axenu/app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./APPBackend/prod.Dockerfile
        workdir: ./APPBackend
